// swap
export const UPDATE_NEO_WALLET_NAME = 'UPDATE_NEO_WALLET_NAME';
export const UPDATE_ETH_WALLET_NAME = 'UPDATE_ETH_WALLET_NAME';

export const UPDATE_NEO_ACCOUNT = 'UPDATE_NEO_ACCOUNT';
export const UPDATE_ETH_ACCOUNT = 'UPDATE_ETH_ACCOUNT';

export const UPDATE_NEO_BALANCES = 'UPDATE_NEO_BALANCES';
export const RESET_NEO_BALANCES = 'RESET_NEO_BALANCES';

export const UPDATE_NEOLINE_IS_MAINNET = 'UPDATE_NEOLINE_IS_MAINNET';
export const UPDATE_METAMASK_CHAIN_ID = 'UPDATE_METAMASK_CHAIN_ID';

export const UPDATE_PENDING_TX = 'UPDATE_PENDING_TX';

// cache
export const CONFIRMED_TX = 'CONFIRMED_TX';
export const ADD_TX = 'ADD_TX';
