// swap
export const UPDATE_NEO_WALLET_NAME = 'UPDATE_NEO_WALLET_NAME';
export const UPDATE_ETH_WALLET_NAME = 'UPDATE_ETH_WALLET_NAME';

export const UPDATE_NEO_ACCOUNT = 'UPDATE_NEO_ACCOUNT';
export const UPDATE_ETH_ACCOUNT = 'UPDATE_ETH_ACCOUNT';

export const UPDATE_NEO_BALANCES = 'UPDATE_NEO_BALANCES';
export const RESET_NEO_BALANCES = 'RESET_NEO_BALANCES';

export const UPDATE_NEOLINE_NETWORK = 'UPDATE_NEOLINE_NETWORK';
export const UPDATE_METAMASK_NETWORK_ID = 'UPDATE_METAMASK_NETWORK_ID';

export const UPDATE_PENDING_TX = 'UPDATE_PENDING_TX';

// setting
export const UPDATE_SETTING = 'UPDATE_SETTING';
