// swap
export const UPDATE_NEO_WALLET_NAME = 'UPDATE_NEO_WALLET_NAME';
export const UPDATE_ETH_WALLET_NAME = 'UPDATE_ETH_WALLET_NAME';

export const UPDATE_NEO_ACCOUNT = 'UPDATE_NEO_ACCOUNT';
export const UPDATE_ETH_ACCOUNT = 'UPDATE_ETH_ACCOUNT';

export const UPDATE_NEO_BALANCES = 'UPDATE_NEO_BALANCES';
export const RESET_NEO_BALANCES = 'RESET_NEO_BALANCES';

export const UPDATE_NEO_IS_MAINNET = 'UPDATE_NEO_IS_MAINNET';

